### PR TITLE
feat: adding welcome controller

### PR DESCRIPTION
**Pull request by abshrv**
** Delete any sections that do not apply **

## Changes

> **Concisely** explain what has changed in this PR. Does your PR require any other PRs to be merged first?  What does a reviewer need to look for? What context will they need?

### How to Test

> Explain the steps to test your PR with enough detail that a person without context will know what to look for. Remember that links are a nice courtesy. Images or animated gifs are even better!

### Code Design

> **If applicable**, add a reference to your code design issue by adding `Resolves #<your code design issue number>`. That will close your code design issue automatically when this PR gets merged.

### User Story / Defect

> **If applicable**, add a link to the user story or defect that this applies to. This will help your reviewer get context.

### Dependencies

> **If applicable**, link to any other PRs that this PR is dependent on. This may be in any repository. This PR should be in WIP until the dependency PR())s get merged.

### CODE REVIEW

**Comment by VinayAdaki** [comment]
Please update description section

**Comment by VinayAdaki** [comment]
@abshrv Please resolve merge conflict for .gitignore

**Comment by abshrv** [comment]
> @abshrv Please resolve merge conflict for .gitignore

Done

**Comment by abshrv** [comment]
> description

Which description? in readme.md?

**Pull request merged**
